project_id = "baxitzkbbqqbbbtojswm"

[functions.bootstrap-user]
verify_jwt = false

[functions.send-goal-notification]
verify_jwt = false

[functions.sales-forecast]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.remove-background]
verify_jwt = false

[functions.ifood-webhook]
verify_jwt = false

[functions.ifood-api]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.debug-redirect]
verify_jwt = false

[functions.manage-organizations]
verify_jwt = false
