project_id = "baxitzkbbqqbbbtojswm"

[functions.bootstrap-user]
verify_jwt = false

[functions.send-goal-notification]
verify_jwt = false

[functions.sales-forecast]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
